add info about local DPSG config
deity-io/falcon-platform-docs pull request #117
Opened 2021-10-18 14:43 UTC by hobadams

This is my understanding of the new changes. Please point me in the right direction if this is incorrect.

2021-10-19 08:53 UTC, Borales commented on dpsg/docs/getting-started/connect.md
> +- `messageQueue.protocol` : string: "" : The protocol used by our message queue. This should be set to `amqp`.
```suggestion
- `messageQueue.protocol` : string: `"amqp"` : The protocol used by our message queue. When used locally - this needs to be set to `amqps`.
```

by default - it's set to `amqp`, thus it doesn't need to be set explicitly.

2021-11-11 08:31 UTC, Borales commented on dpsg/docs/getting-started/connect.md
> +- `messageQueue.protocol` : string: `"amqp"` : The protocol used by our message queue. When used locally - this needs to be set to `amqps`.
@hobadams no, setting a region will be enough for the module to handle the right AMQP host. 

`region` controls the REST API **and** AMQP hosts

2021-11-11 09:37 UTC, Borales requested changes

2021-11-11 09:42 UTC, hobadams commented
@Borales - i think i'm going to close this PR. I think Jonas already covered this stuff. I need to spend some proper time looking over it.

2021-11-11 09:59 UTC, Borales approved these changes

2021-11-11 10:00 UTC, jonas-at-deity approved these changes

2021-11-11 10:20 UTC, merged